# Generated by Django 3.2.8 on 2021-10-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiwoom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='유저ID')),
                ('email', models.EmailField(max_length=100, verbose_name='유저이메일')),
                ('password', models.CharField(max_length=100, verbose_name='유저비밀번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막수정일')),
            ],
            options={
                'verbose_name': '게시판 맴버',
                'verbose_name_plural': '게시판맴버',
                'db_table': 'MemberInfo',
            },
        ),
    ]
